<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Application Summary</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            padding: 30px;
        }

        h2 {
            text-align: center;
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }

        .section {
            margin-top: 20px;
            padding: 15px;
            border: 1px solid #ccc;
            border-radius: 8px;
            background-color: #f9f9f9;
        }

        .row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
        }

        .row strong {
            width: 150px;
            color: #555;
        }

        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>

<body>
    <h2>Application Summary</h2>

    <div class="section">
        <div class="row">
            <strong>Name:</strong>
            <span>{{ $user->name }}</span>
        </div>
        <div class="row">
            <strong>Email:</strong>
            <span>{{ $data['contact_email'] }}</span>
        </div>
        <div class="row">
            <strong>Phone:</strong>
            <span>{{ $data['contact_phone'] }}</span>
        </div>
        <div class="row">
            <strong>Date of Birth:</strong>
            <span>{{ $data['date_of_birth'] }}</span>
        </div>
        <div class="row">
            <strong>Gender:</strong>
            <span>{{ ucfirst($data['gender']) }}</span>
        </div>
        <div class="row">
            <strong>Country:</strong>
            <span>{{ $data['country'] }}</span>
        </div>
        <div class="row">
            <strong>Comments:</strong>
            <span>{{ $data['comments'] ?? null }}</span>
        </div>
    </div>

    <div class="footer">
        Generated by Lighthouse Centre Application System
    </div>
</body>

</html>
